language: php

cache: apt

php:
  #- 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Install Apache
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Configure PHP
  - echo -e "opcache.enable_cli=1\ncgi.fix_pathinfo=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure Apache
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal?g" --in-place /etc/apache2/sites-available/default
  - sudo a2enmod rewrite actions fastcgi alias && sudo service apache2 restart

  # Install Drush
  - composer global require drush/drush:dev-master

  # Download Drupal
  - git clone --depth 1 --branch 8.x http://git.drupal.org/project/drupal.git $TRAVIS_BUILD_DIR/../drupal
  - cd $TRAVIS_BUILD_DIR/../drupal

  # Download dependencies
  - git clone --depth 1 --branch 8.x-1.x http://git.drupal.org/project/key_value.git modules/key_value
  - ln -s $TRAVIS_BUILD_DIR modules/multiversion

  # Copy in test overrides specific to Multiversion.
  - cp $TRAVIS_BUILD_DIR/tests/settings.testing.php sites/default/

  # Install the host site
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing
  - drush --yes pm-enable simpletest

script:
  # Run the tests and make sure we exit with the right status
  - php core/scripts/run-tests.sh --php `which php` --concurrency 7 --url http://127.0.0.1 --xml /tmp "Entity API"
  - if [[ `grep -e 'type="\(failure\|exception\)"\|Fatal error' /tmp/Drupal*` ]]; then cat /tmp/Drupal*; exit 1; fi
