language: php

php:
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

before_install:
  # Update Composer so that the Drush installation doesn't fail.
  - composer selfupdate

install:
  # Install Apache.
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Set up PHP-FPM.
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Set up the Apache vhost.
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Install Drush.
  - composer global require drush/drush:dev-master

  # Checkout a directory structure with all dependencies.
  - git clone --depth 1 --branch 8.x http://git.drupal.org/project/drupal.git $TRAVIS_BUILD_DIR/../drupal
  - git clone --depth 1 --branch 8.x-1.x http://git.drupal.org/project/key_value.git $TRAVIS_BUILD_DIR/../drupal/modules/key_value
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/multiversion

  # Install the site that will host our tests.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing

before_script:
  # Enable required modules and ignore any output to not break the test.
  - drush --yes pm-enable simpletest

script:
  # Run the tests and make sure we exit with the right status.
  - php core/scripts/run-tests.sh --php `which php` --verbose --color --concurrency 4 --url http://127.0.0.1 --xml /tmp --all
  - grep -q -e 'type="\(failure\|exception\)"\|Fatal error' /tmp/Drupal*.xml
  - exit $((1-$?))
